Bugfix/oc 232 minimize user information
OrdinaNederland/to-the-root-backend pull request #9
Opened 2022-04-29 15:52 UTC by DrKlonk

This PR fixes OC-232. It does three things:

- We only return the ids of users with a GET on `/users`
- We only return certain fields of a user with a GET on `/users/:id`
- We remove some fields from the body on a PUT on `/users/me`

2022-05-02 08:04 UTC, dennis-ordina requested changes
More security improvements needed as discussed in Teams call (mostly block user info when fetching other data linked to users, like Likes or Comments). Also make sure Algolia only has the username.

2022-05-02 08:04 UTC, dennis-ordina commented on extensions/users-permissions/services/sanitize-user.js
> +]
Moeten deze hier niet ook nog bij? 

- "has_agreed_to_newsletters_and_notifications",
- "has_agreed_to_ordina_getting_in_touch",
- "number_of_logins",

2022-05-05 08:05 UTC, DrKlonk commented on extensions/users-permissions/services/sanitize-user.js
> +]
Alleen number_of_logins, maar die heb ik eruit gesloopt

2022-05-05 08:23 UTC, dennis-ordina approved these changes

2022-05-05 08:30 UTC, merged